services:
    app.controller.discord:
        class: App\Controller\DiscordController
        public: true
        arguments:
            $discordApiService: '@App\Discord\Service\DiscordApiService'
            $customerRepository: '@sylius.repository.customer'
            $userRepository: '@sylius.repository.app_user'
