imports:
    - { resource: "@SyliusUserBundle/Resources/config/app/config.yml" }

framework:
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'

liip_imagine:
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
                data_root:
                    - '%kernel.project_dir%/public'
    filter_sets:
        # @see http://symfony.com/doc/current/bundles/LiipImagineBundle/filters.html
        cache: ~
        default:
            quality: 100
            filters:
                auto_rotate: ~
                relative_resize: { scale: 1 }
        app_backend_admin_user_avatar_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

sylius_mailer:
    sender:
        name: '%email_name%'
        address: '%email_sender%'
    emails:
        contact_request:
            subject: app.emails.contact_request.subject
            template: emails/contactRequest.html.twig
        user_registration:
            subject: app.emails.user_registration.subject
            template: emails/userRegistration.html.twig
        reset_password_token:
            subject: app.emails.user.password_reset.subject
            template: emails/passwordReset.html.twig
        verification_token:
            subject: app.emails.user.verification_token.subject
            template: emails/verification.html.twig

security:
    password_hashers:
        argon2i: argon2id

vich_uploader:
    mappings:
        admin_avatar:
            uri_prefix: /media/avatar
            upload_destination: '%kernel.project_dir%/public/media/avatar'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
