sylius_ui:
    events:
        sylius.frontend.anime.index.box:
            blocks:
                before_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.frontend.anime.index.before_box
                content:
                    template: "frontend/anime/box/_content.html.twig"
                    priority: 10
                after_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.frontend.anime.index.after_box
