version: '3'

services:
    database:
        container_name: "database"
        image: mariadb:latest
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: simulwatch_explosion
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev

    php:
        container_name: "php-fpm"
        restart: on-failure
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        build:
            context: docker/php
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

        depends_on:
            - database

    nginx:
        container_name: "nginx"
        restart: on-failure
        build:
            context: docker/nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/logs:/var/log
        depends_on:
            - php
        ports:
            - "80:80"
