app_frontend_homepage:
    path: /

    defaults:
        _controller: sylius.controller.anime::indexAction
        _sylius:
            template: 'frontend/anime/index.html.twig'
            grid: sylius_frontend_anime

app_frontend:
    resource: "../sylius/routes/frontend/_main.yaml"
