sylius_frontend_account_dashboard:
    path: /accueil
    methods: [GET]
    defaults:
        _controller: sylius.controller.app_user::showAction
        _sylius:
            template: "frontend/account/dashboard.html.twig"
            repository:
                method: find
                arguments:
                    - expr:service('security.token_storage').getToken().getUser().getId()

sylius_frontend_account_profile_update:
    path: /profile/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.app_user::updateAction
        _sylius:
            template: "frontend/account/updateProfile.html.twig"
            form: App\Form\Type\User\AppUserProfileType
            repository:
                method: find
                arguments:
                    - expr:service('security.token_storage').getToken().getUser().getId()
            flash: sylius.app_user.update_profile
            redirect:
                route: sylius_frontend_account_dashboard
                parameters: {}

sylius_frontend_account_change_password:
    path: /change-password
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.app_user::changePasswordAction
        _sylius:
            template: "frontend/account/changePassword.html.twig"
            redirect: sylius_frontend_account_dashboard
