sylius_frontend_oauth_discord_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: App\Controller\DiscordController::loginAction

sylius_frontend_oauth_discord_start:
    path: /start
    methods: [POST]
    defaults:
        _controller: App\Controller\DiscordController::startAction
