app_backend_dashboard:
    path: /
    defaults:
        _controller: App\Controller\DashboardController::indexAction
        template: 'backend/index.html.twig'

app_backend_partial:
    resource: "partial.yaml"
    prefix: /_partial

sylius_backend_admin_user:
    resource: "admin_user.yaml"

sylius_backend_app_user:
    resource: "app_user.yaml"

sylius_backend_security:
    resource: "security.yaml"

sylius_backend_anime:
    resource: "anime.yaml"

sylius_backend_studio:
    resource: "studio.yaml"

sylius_backend_genre:
    resource: "genre.yaml"
