sylius_grid:
    grids:
        sylius_backend_app_user:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\User\AppUser
            sorting:
                username: asc
            fields:
                avatar:
                    type: twig
                    label: sylius.ui.avatar
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/avatar.html.twig"
                username:
                    type: string
                    label: sylius.ui.username
                    sortable: ~
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ username ]
                username:
                    type: string
                    label: sylius.ui.username
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete



