sylius_grid:
    grids:
        sylius_backend_studio:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Anime\Studio
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ name ]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
